# Generated by Django 2.2 on 2020-12-18 00:32

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201213_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletype',
            options={'ordering': ['priority'], 'verbose_name': '文章类别', 'verbose_name_plural': '文章类别'},
        ),
        migrations.AddField(
            model_name='articletype',
            name='priority',
            field=models.IntegerField(default=-1, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
