# Generated by Django 2.2 on 2020-12-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201218_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=100, verbose_name='论文摘要'),
        ),
    ]
